DROP TABLE IF EXISTS transactions;
DROP TABLE IF EXISTS wallets;
DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS wallets (
    ID SERIAL PRIMARY KEY, FULL_NAME VARCHAR(100), CPF BIGINT, EMAIL VARCHAR(100), "password" VARCHAR(100), "type" INT, BALANCE DECIMAL(10,2)
);

CREATE UNIQUE INDEX IF NOT EXISTS cpf_index ON wallets (CPF);
CREATE UNIQUE INDEX IF NOT EXISTS email_index ON wallets (EMAIL);

CREATE TABLE IF NOT EXISTS transactions (
    ID SERIAL PRIMARY KEY, PAYER INT, PAYEE INT, "value" DECIMAL(10,2),
    CREATED_AT TIMESTAMP,
    FOREIGN KEY (PAYER) REFERENCES wallets (ID),
    FOREIGN KEY (PAYEE) REFERENCES wallets (ID)
);